// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVUrQo6ozfg53-Z4sk6mI59fz8XgMxoE',
    appId: '1:564350382990:web:612fb7c8bc7392a8f62adf',
    messagingSenderId: '564350382990',
    projectId: 'kirra-8c2ac',
    authDomain: 'kirra-8c2ac.firebaseapp.com',
    storageBucket: 'kirra-8c2ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrG4TD81gJ7BSAQgMCCL8ghmGqyGlgkKM',
    appId: '1:564350382990:android:bb261056aee7c402f62adf',
    messagingSenderId: '564350382990',
    projectId: 'kirra-8c2ac',
    storageBucket: 'kirra-8c2ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6j6zsUSumUBCrvlSXCbCEOUTib9CItkk',
    appId: '1:564350382990:ios:c21826ea4c577d29f62adf',
    messagingSenderId: '564350382990',
    projectId: 'kirra-8c2ac',
    storageBucket: 'kirra-8c2ac.firebasestorage.app',
    iosBundleId: 'com.example.kirra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6j6zsUSumUBCrvlSXCbCEOUTib9CItkk',
    appId: '1:564350382990:ios:c21826ea4c577d29f62adf',
    messagingSenderId: '564350382990',
    projectId: 'kirra-8c2ac',
    storageBucket: 'kirra-8c2ac.firebasestorage.app',
    iosBundleId: 'com.example.kirra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVUrQo6ozfg53-Z4sk6mI59fz8XgMxoE',
    appId: '1:564350382990:web:dac8a54a71854705f62adf',
    messagingSenderId: '564350382990',
    projectId: 'kirra-8c2ac',
    authDomain: 'kirra-8c2ac.firebaseapp.com',
    storageBucket: 'kirra-8c2ac.firebasestorage.app',
  );
}

